books/urls.py
from django.urls import path
from . import views
app_name = 'books'

urlpatterns = [
    path('', views.index),
    path('login', views.login),
]

labWithTests/urls.py
from django.contrib import admin
from django.urls import path, include
from status import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('status.urls')),
    path('subscribe/', include('subscription.urls')),
    path('books/', include('books.urls')),
]

status/urls.py
from django.contrib import admin
from django.urls import path
from status import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('profile',views.profile, name='profile')
]

subscription/urls.py
from django.urls import path
from . import views

app_name = 'subscription'

urlpatterns = [
    path('', views.index, name='index'),
    path('subscribers', views.subscriber_list, name='subscriber_list'),
    path('unsubscribe', views.unsubscribe, name='unsubscribe')
]

books/models.py
from django.db import models

# Create your models here.

status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    text = models.TextField(default='')
    time = models.DateTimeField(null=True)

subscription/models.py
from django.db import models

class Subscription(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=20, default='')
    password = models.CharField(max_length=20)

books/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect
import requests
import json

from google.oauth2 import id_token
from google.auth.transport import requests as grequests

def index(req):
    if req.method == 'POST' and req.is_ajax():
        data = json.loads(req.body)
        if (data['type'] == 'postFavorite'):
            newCount = int(data['favCount']) + 1
            req.session['favCount'] = str(newCount)
            return JsonResponse({'favCount' : str(newCount)})
        elif (data['type'] == 'postKeyword'):
            keyword = data['keyword']
            r = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + keyword)
            res = r.json()
            req.session['favCount'] = '0'
            return JsonResponse({'items' : res['items'], 'keyword': keyword, 'favCount': 0})
        else:
            return JsonResponse({'error': 'Unknown type'})

    else:
        try:
            userid = req.session['userid']
            r = requests.get('https://www.googleapis.com/books/v1/volumes?q=quilting')
            res = r.json()
            req.session['favCount'] = '0'
            return render(req, 'books.html', {'books': res['items'], 'favCount': 0, 'keyword': 'quilting'})
        except KeyError:
            return HttpResponseRedirect('login')

def login(req):
    if req.method == 'POST' and req.is_ajax():
        data = json.loads(req.body)
        if (data['type'] == 'googleAuth'):
            try:
                # Specify the CLIENT_ID of the app that accesses the backend:
                idinfo = id_token.verify_oauth2_token(data['idToken'], grequests.Request(), '836085326501-hulpvrrhnagkha9fp1hljcj7vvs531v0.apps.googleusercontent.com')

                if idinfo['iss'] not in ['accounts.google.com', 'https://accounts.google.com']:
                    raise ValueError('Wrong issuer.')

                # ID token is valid. Get the user's Google Account ID from the decoded token.
                userid = idinfo['sub']
                req.session['userid'] = userid
                req.session['name'] = data['name']
                req.session['imgUrl'] = data['imgUrl']
                req.session['email'] = data['email']
                return JsonResponse({'url': 'http://localhost:8000/books/'})
            except ValueError:
                return JsonResponse({'error': 'Invalid Google Auth token'})
        elif (data['type'] == 'googleLogout'):
            del req.session['userid']
            del req.session['name']
            del req.session['imgUrl']
            del req.session['email']
            return JsonResponse({'url': 'http://localhost:8000/books/login'})
        else:
            return JsonResponse({'error': 'Unknown type'})
    else:
        return render(req, 'login.html')

status/views.py
from django.shortcuts import render, redirect
from .models import Status
from datetime import datetime

def profile(req):
    return render(req, 'profile.html')

def landing(req):
    if req.method == 'POST':
        new_status = req.POST['status_text']
        Status.objects.create(text = new_status, time=datetime.now())
        return redirect('/')

    entries = Status.objects.all()
    return render(req, 'landing.html', {'entries': entries})

subscription/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import Subscription
import json

def index(req):
    if req.method == 'POST' and req.is_ajax():
        data = json.loads(req.body)
        if (data['type'] == 'checkEmailRegistered'):
            isRegistered = Subscription.objects.all().filter(email=data['email']).exists()
            return JsonResponse({'registered': isRegistered})
        elif data['type'] == 'postSubscription':
            Subscription.objects.create(email=data['email'], name=data['name'], password=data['password'])
            return JsonResponse({'message' : 'Data berhasil disimpan!'})
        else:
            return JsonResponse({'message': 'Unknown action', 'error': True})
    else:
        return render(req, 'subscription.html')

def unsubscribe(req):
    if req.method == 'POST' and req.is_ajax():
        data = json.loads(req.body)
        if data['type'] == 'unsubscribe':
            user = Subscription.objects.all().filter(email=data['email'])[0]
            print(data)
            if (data['password'] == user.password):
                user.delete()
                return JsonResponse({'message': 'Unsubscribe successful', 'error': False})
            else:
                return JsonResponse({'message': 'Incorrect password, please try again', 'error': True})
    return JsonResponse({'message': 'Unknown action', 'error': True})

def subscriber_list(req):
    subscribers = Subscription.objects.all().values()
    return JsonResponse({'subscribers': list(subscribers)})

books/templates/books.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <meta name="google-signin-client_id" content="836085326501-hulpvrrhnagkha9fp1hljcj7vvs531v0.apps.googleusercontent.com">
</head>
<body>
  <div class="container">
    <div class="d-flex flex-row justify-content-between">
      <div>
        <h1 name="title">Books</h1>
        <h5>Favorited: <span id="favCount">{{ favCount }}</span></h5>
        <h5>Keyword: <span id="keyword">{{ keyword }}</span></h5>
      </div>
      <div>
        <div class="d-flex flex-row justify-content-between">
          <img src="{{ request.session.imgUrl }}" alt="userimg">
          <p>{{ request.session.name }}</p>
          <p id="googleuserid" style="display: none;">{{ request.session.userid }}</p>
        </div>
        <div>
          <a href="#" onclick="signOut();">Sign out</a>
        </div>
      </div>
    </div>
    <form method="post">
      {% csrf_token %}
      <div class="input-group mb-3">
        <input type="text" id="keywordField" onsubmit="postKeyword(event)" class="form-control" placeholder="Keyword" aria-label="Keyword" aria-describedby="button-addon2" />
        <div class="input-group-append">
          <button onclick="postKeyword(event)" class="btn btn-secondary" id="button-addon2">Search</button>
        </div>
      </div>
    </form>
    <div class="card">
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">No</th>
            <th scope="col">Title</th>
            <th scope="col">Publisher</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for book in books %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ book.volumeInfo.title }}</td>
            <td>{{ book.volumeInfo.publisher }}</td>
            <td>
              <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-success" onclick='postFavorite(event, "{{ book.volumeInfo.title }})")'>Add to favourite</button></td>
              </form>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>
  <script src="{% static 'js/books.js' %}" charset="utf-8"></script>
</body>
</html>

books/templates/login.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Login</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  
  <meta name="google-signin-scope" content="profile email">
  <meta name="google-signin-client_id" content="836085326501-hulpvrrhnagkha9fp1hljcj7vvs531v0.apps.googleusercontent.com">
  <script src="https://apis.google.com/js/platform.js" async defer></script>
  <script src="{% static 'js/books.js' %}" charset="utf-8"></script>
</head>
<body>
  <div class="container">
    <h1>Login</h1>
    <form>{% csrf_token %}</form>
    <div class="g-signin2" data-onsuccess="onSignIn"></div>
  </div>
</body>
</html>

status/templates/landing.html
{% load static from staticfiles %}
<html>
  <head>
    <title>Landing Page</title>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/global-styles.css' %}">
  </head>
  <body class="landing">
    <div class="container">
      <div class="box">
        <h1>Hello, Apa kabar?</h1>
        <form action="" method="post">
          {% csrf_token %}
          <input type="text" id="input" placeholder="Status hari ini" name="status_text">
          <input type="submit" value="Submit">
        </form>
        <a href="{% url 'subscription:index' %}" class="btn btn-success my-3">Subscribe</a>

        {% for e in entries %}
        <div class="status">
          <p>
            <b>{{ e.text }}</b><br>
            <span class="status-time">on {{ e.time }}</span>
          </p>
        </div>
        {% endfor %}
      </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/script.js' %}" charset="utf-8"></script>
  </body>
</html>

status/templates/profile.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Profile Page</title>
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet" href="{% static 'css/global-styles.css' %}">
</head>
<body class="profile">
  <section class="loading">
    <h1>Loading page..</h1>
    <div class="sk-cube-grid">
      <div class="sk-cube sk-cube1"></div>
      <div class="sk-cube sk-cube2"></div>
      <div class="sk-cube sk-cube3"></div>
      <div class="sk-cube sk-cube4"></div>
      <div class="sk-cube sk-cube5"></div>
      <div class="sk-cube sk-cube6"></div>
      <div class="sk-cube sk-cube7"></div>
      <div class="sk-cube sk-cube8"></div>
      <div class="sk-cube sk-cube9"></div>
    </div>
  </section>
  <header style="display: none">
    <div class="box text-center">
      <h1>Hello, my name is Dave</h1>
      <p>Page ini dibuat untuk kepentingan challenge PPW dan tidak ada konten yang penting.</p>
      <button id="theme-changer">Ganti Tema</button>
    </div>
    <section class="container">
      <div class="box">
        <h2>Aktivitas dan Pengalaman</h2>
        <div class="accordion">
          <h3>Belajar</h3>
          <div>
            <p>
              Saya suka belajar.
            </p>
          </div>
          <h3>Bermain Musik</h3>
          <div>
            <p>
              Saya suka bermain piano.
            </p>
          </div>
          <h3>Makan</h3>
          <div>
            <p>
              Saya suka makan.
            </p>
          </div>
        </div>

        <h2>Organisasi dan Kepanitiaan</h2>
        <div class="accordion">
          <h3>PTI BEM FASILKOM 2018</h3>
          <div>
            <p>
              Sebagai staf biro PTI
            </p>
          </div>
          <h3>Coming soon</h3>
          <div>
            <p>
              Belum ada.
            </p>
          </div>
          <h3>Coming soon</h3>
          <div>
            <p>
              Belum ada.
            </p>
          </div>
        </div>
        <h2>Prestasi</h2>
        <div class="accordion">
          <h3>Coming soon</h3>
          <div>
            <p>
              Belum ada.
            </p>
          </div>
          <h3>Coming soon</h3>
          <div>
            <p>
              Belum ada.
            </p>
          </div>
          <h3>Coming soon</h3>
          <div>
            <p>
              Belum ada.
            </p>
          </div>
        </div>
      </div>
    </section>
  </header>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

subscription/templates/subscription.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Subscribe to my website</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
</head>
<body>
  <div class="container">
    <h1>Subscribe</h1>
    <p id="info" style="display: none;"></p>
    <form>
      {% csrf_token %}
      <div class="form-group">
        <label for="emailfield">Email address</label>
        <input type="email" class="form-control" id="emailfield" aria-describedby="emailHelp" placeholder="Email" required>
        <div class="validFeedback">
        </div>
        <div class="invalidFeedback">
        </div>
      </div>
      <div class="form-group">
        <label for="passwordfield">Name</label>
        <input type="text" class="form-control" id="namefield" placeholder="Name" required>
      </div>
      <div class="form-group">
        <label for="passwordfield">Password</label>
        <input type="password" class="form-control" id="passwordfield" placeholder="Password" required>
      </div>
      <button class="btn btn-primary" type="submit" id="submitButton" onclick="postSubscription(event)">Subscribe</button>
    </form>

    <section id="subscribers">

    </section>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <script src="{% static 'js/subscription.js' %}" charset="utf-8"></script>
</body>
</html>